import type { WorkspaceData } from "./fixtures";

const headers = (key?: string) => ({ "Content-Type": "application/json", "X-Dev-Identity": "operator", ...(key ? { "Idempotency-Key": key } : {}) });
async function request<T>(path: string, init: RequestInit = {}): Promise<T> { const response = await fetch(`/api/v1${path}`, init); if (!response.ok) { const problem = await response.json().catch(() => ({})); throw new Error(problem.detail ?? `API request failed (${response.status})`); } return response.json() as Promise<T>; }
type Candidate = { action: string; rank: number; confidence: string; expected_operational_effect: string; resource_cost: Record<string, string | number>; excluded_resources: Record<string, string> };
type Recommendation = { id: string; status: string; candidates: Candidate[]; compatible_resources: Array<{ id: string; name: string }>; queue_item_id?: string; auto_dispatched: boolean };
type Scenario = { replayed_at: string; signals: { water_runway_hours: number; contamination: string; population_influx: number } };
type Item = Record<string, unknown>;
export type GoldenFlow = { data: WorkspaceData; recommendation: Recommendation; audit: Item[] };

function mapWorkspace(scenario: Scenario, recommendation: Recommendation, resources: Item[], queue: Item[], verification: Item[], tasks: Item[]): WorkspaceData {
  return {
    projections: [{ resource: "Potable water", time: `${scenario.signals.water_runway_hours} h`, state: "critical next", freshness: "Live replay · runway_v1" }, { resource: "Water contamination", time: scenario.signals.contamination, state: "operational pressure", freshness: "Synthetic replay signal" }, { resource: "Population influx", time: `+${scenario.signals.population_influx}`, state: "expected", freshness: "Contradictory · verify" }],
    candidates: recommendation.candidates.map((item) => ({ action: item.action.replaceAll("_", " "), rank: item.rank, confidence: item.confidence, effect: item.expected_operational_effect, cost: Object.entries(item.resource_cost).map(([key, value]) => `${key}: ${value}`).join(" · "), excluded: Object.entries(item.excluded_resources).map(([id, reason]) => `${id}: ${reason}`).join("; ") || "None" })),
    evidence: [{ id: "scenario_fixed_north_sector_v1", claim: "North Sector coupled water/power pressure", state: "replayed", source: `Backend · ${scenario.replayed_at}` }, { id: "verification-live", claim: "Population influx requires confirmation", state: "unknown / visible", source: "Backend verification queue" }],
    resources: resources.map((item) => ({ id: String(item.id), name: String(item.name), readiness: String(item.readiness).toUpperCase(), route: item.readiness_expires_at ? `Fresh until ${String(item.readiness_expires_at)}` : "Freshness unknown", task: tasks.some((task) => task.resource_id === item.id && task.status !== "completed") ? "Active task" : "Unassigned" })),
    queue: [...queue, ...verification].map((item) => ({ id: String(item.id), title: String(item.title), status: String(item.status ?? item.queue_type) })),
    tasks: tasks.map((item) => ({ id: String(item.id), resource: String(item.resource_id), status: String(item.status), outcome: String(item.outcome_summary ?? "Outcome pending") })),
    places: [{ id: "north-sector", label: "North Sector · coupled shelter pressure", state: "synthetic replay", coordinates: "bounded location withheld" }],
  };
}
async function reads(scenario: Scenario, recommendation: Recommendation): Promise<GoldenFlow> { const [resources, queue, verification, tasks, audit] = await Promise.all([request<{ items: Item[] }>("/resources", { headers: headers() }), request<{ items: Item[] }>("/response-queue", { headers: headers() }), request<{ items: Item[] }>("/verification-queue", { headers: headers() }), request<{ items: Item[] }>("/tasks", { headers: headers() }), request<{ items: Item[] }>("/decision-loop/audit", { headers: headers() })]); return { data: mapWorkspace(scenario, recommendation, resources.items, queue.items, verification.items, tasks.items), recommendation, audit: audit.items }; }
export async function resetGoldenFlow(): Promise<GoldenFlow> { const run = Date.now(); const scenario = await request<Scenario>("/decision-loop/demo/replay", { method: "POST", headers: headers(`ui-replay-${run}`) }); const recommendation = await request<Recommendation>("/decision-loop/recommendations", { method: "POST", headers: headers(`ui-recommend-${run}`) }); return reads(scenario, recommendation); }
export async function decide(flow: GoldenFlow, decision: "approve" | "reject"): Promise<GoldenFlow> { const recommendation = await request<Recommendation>(`/decision-loop/recommendations/${flow.recommendation.id}/decision`, { method: "POST", headers: headers(`ui-decision-${Date.now()}`), body: JSON.stringify({ decision, note: "Commander decision from operator workspace" }) }); const scenario = await request<Scenario>("/decision-loop/scenario", { headers: headers() }); return reads(scenario, recommendation); }
export async function assignApproved(flow: GoldenFlow): Promise<GoldenFlow> { const queueId = flow.recommendation.queue_item_id; const resourceId = flow.recommendation.compatible_resources[0]?.id; if (!queueId || !resourceId) throw new Error("No approved queue item or compatible resource"); const now = new Date(); await request("/route-observations", { method: "POST", headers: headers(`ui-route-${Date.now()}`), body: JSON.stringify({ destination: "North Sector", state: "passable", observed_at: now.toISOString(), expires_at: new Date(now.getTime() + 3600000).toISOString(), source: "commander_demo_confirmation" }) }); await request(`/response-queue/${queueId}/approve`, { method: "POST", headers: headers(`ui-assign-${Date.now()}`), body: JSON.stringify({ resource_id: resourceId, approved: true, approval_note: "Commander confirmed route and manual assignment" }) }); const scenario = await request<Scenario>("/decision-loop/scenario", { headers: headers() }); return reads(scenario, flow.recommendation); }
export async function advanceTask(flow: GoldenFlow, status: "acknowledged" | "en_route" | "completed"): Promise<GoldenFlow> { const task = flow.data.tasks.find((item) => item.status !== "completed"); if (!task) throw new Error("No active task"); await request(`/tasks/${task.id}`, { method: "PATCH", headers: headers(`ui-task-${status}-${Date.now()}`), body: JSON.stringify({ status }) }); if (status === "completed") await request(`/tasks/${task.id}/outcome`, { method: "POST", headers: headers(`ui-outcome-${Date.now()}`), body: JSON.stringify({ summary: "Synthetic water continuity intervention completed" }) }); const scenario = await request<Scenario>("/decision-loop/scenario", { headers: headers() }); return reads(scenario, flow.recommendation); }
