import type { Plan, ResourceForecast, ResourceRequest, Unlock, Verification, WorkspaceData } from "./fixtures";

const headers = (key?: string) => ({ "Content-Type": "application/json", "X-Dev-Identity": "operator", ...(key ? { "Idempotency-Key": key } : {}) });
async function request<T>(path: string, init: RequestInit = {}): Promise<T> { const response = await fetch(`/api/v1${path}`, init); if (!response.ok) { const problem = await response.json().catch(() => ({})); throw new Error(problem.detail ?? `API request failed (${response.status})`); } return response.json() as Promise<T>; }
type Candidate = { action: string; rank: number; confidence: string; expected_operational_effect: string; resource_cost: Record<string, string | number>; excluded_resources: Record<string, string> };
type Recommendation = { id: string; status: string; candidates: Candidate[]; compatible_resources: Array<{ id: string; name: string }>; queue_item_id?: string; auto_dispatched: boolean };
type Scenario = { replayed_at: string; signals: { water_runway_hours: number; contamination: string; population_influx: number } };
export type CommandIncident = { incident_id: string; name: string; hazard_type: string; severity: string; operational_period: string; summary: string; event_time: string; status: string; phase: string; roles: Record<string, string> };
export type IncidentSector = { sector_id: string; incident_id: string; name: string; owner_actor_id: string; assessment_state: string };
export type EvidenceReport = { id: string; report_type: string; status: string; source: { channel: string; source_class: string }; observed_at: string | null; recorded_at: string; location: { place_text: string | null; uncertainty_m: number | null } | null; warnings: string[]; revision: number };
export type EvidenceReportDetail = EvidenceReport & { claims: Array<{ id: string; claim_type: string; value: unknown; verification_state: string }>; duplicate_candidates: Array<{ candidate_report_id: string; reason: string }>; command_incident_links: Array<{ incident_id: string; linked_by: string; linked_at: string }> };
export type MapFeature = { id: string; geometry: { type: string; coordinates: unknown }; properties: Record<string, unknown> };
export type Mission = { mission_id: string; id: string; title: string; status: string; destination: string | null; required_capability: string | null; source_report_id: string; task: { id: string; status: string } | null };
type Item = Record<string, unknown>;
export type GoldenFlow = { data: WorkspaceData; recommendation: Recommendation; audit: Item[]; activeIncident?: CommandIncident | null };

function mapWorkspace(scenario: Scenario, recommendation: Recommendation, resources: Item[], queue: Item[], verification: Verification[], unlocks: Unlock[], plans: Plan[], forecasts: ResourceForecast[], resourceRequests: ResourceRequest[], tasks: Item[]): WorkspaceData {
  return {
    projections: [{ resource: "Potable water", time: `${scenario.signals.water_runway_hours} h`, state: "critical next", freshness: "Live replay · runway_v1" }, { resource: "Water contamination", time: scenario.signals.contamination, state: "operational pressure", freshness: "Synthetic replay signal" }, { resource: "Population influx", time: `+${scenario.signals.population_influx}`, state: "expected", freshness: "Contradictory · verify" }],
    candidates: recommendation.candidates.map((item) => ({ action: item.action.replaceAll("_", " "), actionId: item.action, rank: item.rank, confidence: item.confidence, effect: item.expected_operational_effect, cost: Object.entries(item.resource_cost).map(([key, value]) => `${key}: ${value}`).join(" · "), excluded: Object.entries(item.excluded_resources).map(([id, reason]) => `${id}: ${reason}`).join("; ") || "None" })),
    evidence: [{ id: "scenario_fixed_north_sector_v1", claim: "North Sector coupled water/power pressure", state: "replayed", source: `Backend · ${scenario.replayed_at}` }],
    resources: resources.map((item) => ({ id: String(item.id), name: String(item.name), readiness: String(item.readiness).toUpperCase(), route: item.readiness_expires_at ? `Fresh until ${String(item.readiness_expires_at)}` : "Freshness unknown", task: tasks.some((task) => task.resource_id === item.id && task.status !== "completed") ? "Active task" : "Unassigned" })),
    queue: queue.map((item) => ({ id: String(item.id), title: String(item.title), status: String(item.status ?? item.queue_type) })),
    tasks: tasks.map((item) => ({ id: String(item.id), resource: String(item.resource_id), status: String(item.status), outcome: String(item.outcome_summary ?? "Outcome pending") })),
    places: [{ id: "north-sector", label: "North Sector · coupled shelter pressure", state: "synthetic replay", coordinates: "bounded location withheld" }],
    verification,
    unlocks,
    plans,
    forecasts,
    resourceRequests,
  };
}
async function reads(scenario: Scenario, recommendation: Recommendation): Promise<GoldenFlow> { const [resources, queue, verificationQueue, tasks, audit, coverage, infrastructure, plans, forecasts, resourceRequests] = await Promise.all([request<{ items: Item[] }>("/resources", { headers: headers() }), request<{ items: Item[] }>("/response-queue", { headers: headers() }), request<{ items: Item[] }>("/verification-queue", { headers: headers() }), request<{ items: Item[] }>("/tasks", { headers: headers() }), request<{ items: Item[] }>("/decision-loop/audit", { headers: headers() }), request<{ items: Verification[] }>("/coverage/verification-ranking", { headers: headers() }), request<{ items: Unlock[] }>("/infrastructure/unlock-ranking", { headers: headers() }), request<{ items: Plan[] }>("/plans", { headers: headers() }), request<{ items: ResourceForecast[] }>("/resource-forecasts", { headers: headers() }), request<{ items: ResourceRequest[] }>("/resource-requests", { headers: headers() })]); return { data: mapWorkspace(scenario, recommendation, resources.items, [...queue.items, ...verificationQueue.items], coverage.items, infrastructure.items, plans.items, forecasts.items, resourceRequests.items, tasks.items), recommendation, audit: audit.items }; }
export async function resetGoldenFlow(): Promise<GoldenFlow> { const run = Date.now(); const scenario = await request<Scenario>("/decision-loop/demo/replay", { method: "POST", headers: headers(`ui-replay-${run}`) }); const recommendation = await request<Recommendation>("/decision-loop/recommendations", { method: "POST", headers: headers(`ui-recommend-${run}`) }); return reads(scenario, recommendation); }
export async function getActiveIncident(): Promise<CommandIncident | null> { const result = await request<{ incident: CommandIncident | null }>("/command/incidents/active", { headers: headers() }); return result.incident; }
export async function listIncidentSectors(incidentId: string): Promise<IncidentSector[]> { const result = await request<{ items: IncidentSector[] }>(`/command/incidents/${incidentId}/sectors`, { headers: headers() }); return result.items; }
export async function createIncidentSector(incidentId: string, input: { name: string; owner_actor_id: string }): Promise<IncidentSector> { return request<IncidentSector>(`/command/incidents/${incidentId}/sectors`, { method: "POST", headers: headers(`ui-sector-${incidentId}-${Date.now()}`), body: JSON.stringify(input) }); }
export async function listEvidenceReports(): Promise<EvidenceReport[]> { return (await request<{ items: EvidenceReport[] }>("/reports", { headers: headers() })).items; }
export async function getEvidenceReport(reportId: string): Promise<EvidenceReportDetail> { return request<EvidenceReportDetail>(`/reports/${reportId}`, { headers: headers() }); }
export async function createEvidenceReport(input: { report_type: string; place_text: string; people_affected: number | null; longitude?: number; latitude?: number }): Promise<{ report_id: string }> { const clientRecordId = `rpt_ui_${crypto.randomUUID()}`; const observedAt = new Date().toISOString(); return request("/reports", { method: "POST", headers: headers(clientRecordId), body: JSON.stringify({ contract_version: 1, client_record_id: clientRecordId, observed_at: observedAt, received_at: observedAt, source: { channel: "operator_report_desk", source_class: "authenticated_operator" }, location: { geometry: { type: "Point", coordinates: [input.longitude ?? 91.742, input.latitude ?? 26.184] }, uncertainty_m: 250, place_text: input.place_text || null }, report_type: input.report_type, facts: { people_affected: input.people_affected, access_state: "unknown" }, privacy_class: "restricted_operational" }) }); }
export async function reviewEvidenceReport(reportId: string, claimUpdates: Record<string, string>): Promise<EvidenceReportDetail> { return request(`/reports/${reportId}/review`, { method: "POST", headers: headers(`ui-review-${reportId}-${Date.now()}`), body: JSON.stringify({ claim_updates: claimUpdates, note: "Commander review from report desk" }) }); }
export async function linkEvidenceToCommandIncident(reportId: string, incidentId: string): Promise<void> { await request(`/reports/${reportId}/command-incident-links`, { method: "POST", headers: headers(`ui-report-link-${reportId}-${Date.now()}`), body: JSON.stringify({ incident_id: incidentId }) }); }
export async function assignVerification(report: EvidenceReportDetail, incidentId: string | undefined): Promise<void> { const key = `ui-verify-${report.id}-${Date.now()}`; await request("/verification-queue", { method: "POST", headers: headers(key), body: JSON.stringify({ title: `Verify ${report.report_type.replaceAll("_", " ")}`, priority: "high", destination: report.location?.place_text ?? null, notes: "Human verification requested from report desk", owner_actor_id: "operator", source_report_id: report.id, source_incident_id: incidentId ?? null }) }); }
export async function listMapFeatures(): Promise<MapFeature[]> { return (await request<{ features: MapFeature[] }>("/map/features?limit=100", { headers: headers() })).features; }
export async function listMissions(): Promise<Mission[]> { return (await request<{ items: Mission[] }>("/missions", { headers: headers() })).items; }
export async function createMission(input: { source_report_id: string; source_incident_id: string; objective: string; destination: string; required_capability: string }): Promise<Mission> { return request("/missions", { method: "POST", headers: headers(`ui-mission-${Date.now()}`), body: JSON.stringify({ ...input, priority: "high", owner_actor_id: "operator" }) }); }
export async function listResources(): Promise<Array<{ id: string; name: string; readiness: string }>> { return (await request<{ items: Array<{ id: string; name: string; readiness: string }> }>("/resources", { headers: headers() })).items; }
export async function listResourceForecasts(): Promise<ResourceForecast[]> { return (await request<{ items: ResourceForecast[] }>("/resource-forecasts", { headers: headers() })).items; }
export async function listResourceRequests(): Promise<ResourceRequest[]> { return (await request<{ items: ResourceRequest[] }>("/resource-requests", { headers: headers() })).items; }
export async function approveMission(missionId: string, resourceId: string): Promise<void> { await request(`/response-queue/${missionId}/approve`, { method: "POST", headers: headers(`ui-mission-approval-${missionId}-${Date.now()}`), body: JSON.stringify({ resource_id: resourceId, approved: true, approval_note: "Commander approved mission assignment" }) }); }
export async function advanceLiveTask(taskId: string, status: "acknowledged" | "en_route" | "on_scene" | "paused"): Promise<void> { await request(`/tasks/${taskId}`, { method: "PATCH", headers: headers(`ui-live-task-${taskId}-${status}-${Date.now()}`), body: JSON.stringify({ status }) }); }
export async function completeLiveTask(taskId: string, actionTypeEvidence: string): Promise<void> { const completedAt = new Date().toISOString(); await request(`/tasks/${taskId}`, { method: "PATCH", headers: headers(`ui-live-task-complete-${taskId}-${Date.now()}`), body: JSON.stringify({ status: "completed" }) }); await request(`/tasks/${taskId}/structured-outcome`, { method: "POST", headers: headers(`ui-live-outcome-${taskId}-${Date.now()}`), body: JSON.stringify({ action_type_evidence: actionTypeEvidence, completion_quantities: {}, completed_at: completedAt, residual_need: null, verified_by: "operator" }) }); }
export async function createSitrep(reports: EvidenceReport[]): Promise<{ reports: number; by_type: Record<string, number>; summary_hash: string }> { return request("/exports/sitrep", { method: "POST", headers: headers(), body: JSON.stringify({ tenant_id: "org_demo", workspace_id: "evt_demo", replay_at: new Date().toISOString(), rows: reports.map((report) => ({ event_time: report.observed_at ?? report.recorded_at, report_type: report.report_type, status: report.status, location: report.location?.place_text ?? "unknown" })) }) }); }
export async function runExerciseReplay(): Promise<{ record_count: number; future_records_excluded: number; scenario_signals: string[]; result_hash: string; synthetic: boolean }> { return request("/evaluation/replay", { headers: headers() }); }
export type PilotStatus = { configuration: { agency_name: string; district_name: string; country_code: string; approved_feed_ids: string[]; retention_days_operational: number; retention_days_restricted: number } | null; official_feed_events: number; identity_mode: string; retention_enforcement: string };
export type TabletopExercise = { synthetic: boolean; faults: string[]; metrics: { verification_time_minutes: number; wrong_dispatches: number; duplicate_missions_prevented: number; coverage_gaps_surfaced: number; sync_delay_minutes: number; operator_actions: number }; result_hash: string; limitations: string[] };
export async function getPilotStatus(): Promise<PilotStatus> { return request("/pilot/status", { headers: headers() }); }
export async function configurePilot(input: { agency_name: string; district_name: string; country_code: string; approved_feed_ids: string[] }): Promise<PilotStatus["configuration"]> { return request("/pilot/configuration", { method: "PUT", headers: headers(`ui-pilot-config-${Date.now()}`), body: JSON.stringify({ ...input, retention_days_operational: 90, retention_days_restricted: 30, hazard_playbooks: { flood: "flood_v1", earthquake: "earthquake_v1", landslide: "landslide_v1" } }) }); }
export async function runPilotTabletop(): Promise<TabletopExercise> { return request("/pilot/exercises/tabletop", { method: "POST", headers: headers(`ui-pilot-tabletop-${Date.now()}`) }); }
export async function activateIncident(input: { name: string; hazard_type: string; severity: string; summary: string; event_time: string }): Promise<CommandIncident> { const created = await request<CommandIncident>("/command/incidents", { method: "POST", headers: headers(`ui-incident-create-${Date.now()}`), body: JSON.stringify(input) }); await request(`/command/incidents/${created.incident_id}/roles`, { method: "POST", headers: headers(`ui-incident-role-${created.incident_id}`), body: JSON.stringify({ role: "incident_commander", actor_id: "operator" }) }); return request<CommandIncident>(`/command/incidents/${created.incident_id}`, { method: "PATCH", headers: headers(`ui-incident-activate-${created.incident_id}`), body: JSON.stringify({ status: "active", phase: "activation", note: "Incident activated from command room" }) }); }
export async function pauseIncident(incidentId: string): Promise<CommandIncident> { return request<CommandIncident>(`/command/incidents/${incidentId}`, { method: "PATCH", headers: headers(`ui-incident-pause-${incidentId}-${Date.now()}`), body: JSON.stringify({ status: "paused", phase: "handover", note: "Paused by commander from command bar" }) }); }
export async function resumeIncident(incidentId: string): Promise<CommandIncident> { return request<CommandIncident>(`/command/incidents/${incidentId}`, { method: "PATCH", headers: headers(`ui-incident-resume-${incidentId}-${Date.now()}`), body: JSON.stringify({ status: "active", phase: "size_up", note: "Resumed by commander from paused-session landing" }) }); }
export async function closeIncident(incidentId: string): Promise<CommandIncident> { return request<CommandIncident>(`/command/incidents/${incidentId}`, { method: "PATCH", headers: headers(`ui-incident-close-${incidentId}-${Date.now()}`), body: JSON.stringify({ status: "closed", phase: "handover", note: "Closed by commander from paused-session landing" }) }); }
export async function decide(flow: GoldenFlow, decision: "approve" | "reject", selectedAction?: string): Promise<GoldenFlow> { const recommendation = await request<Recommendation>(`/decision-loop/recommendations/${flow.recommendation.id}/decision`, { method: "POST", headers: headers(`ui-decision-${Date.now()}`), body: JSON.stringify({ decision, selected_action: selectedAction, note: "Commander decision from operator workspace" }) }); const scenario = await request<Scenario>("/decision-loop/scenario", { headers: headers() }); return reads(scenario, recommendation); }
export async function approveMutualAid(flow: GoldenFlow, requestId: string): Promise<GoldenFlow> { await request(`/resource-requests/${requestId}/approve`, { method: "PATCH", headers: headers(`ui-mutual-aid-approval-${requestId}-${Date.now()}`), body: JSON.stringify({ approved: true, approval_note: "Commander approved synthetic mutual-aid request" }) }); const scenario = await request<Scenario>("/decision-loop/scenario", { headers: headers() }); return reads(scenario, flow.recommendation); }
export async function assignApproved(flow: GoldenFlow): Promise<GoldenFlow> { const queueId = flow.recommendation.queue_item_id; const resourceId = flow.recommendation.compatible_resources[0]?.id; if (!queueId || !resourceId) throw new Error("No approved queue item or compatible resource"); const now = new Date(); await request("/route-observations", { method: "POST", headers: headers(`ui-route-${Date.now()}`), body: JSON.stringify({ destination: "North Sector", state: "passable", observed_at: now.toISOString(), expires_at: new Date(now.getTime() + 3600000).toISOString(), source: "commander_demo_confirmation" }) }); await request(`/response-queue/${queueId}/approve`, { method: "POST", headers: headers(`ui-assign-${Date.now()}`), body: JSON.stringify({ resource_id: resourceId, approved: true, approval_note: "Commander confirmed route and manual assignment" }) }); const scenario = await request<Scenario>("/decision-loop/scenario", { headers: headers() }); return reads(scenario, flow.recommendation); }
export async function advanceTask(flow: GoldenFlow, status: "acknowledged" | "en_route" | "on_scene" | "paused" | "completed"): Promise<GoldenFlow> { const task = flow.data.tasks.find((item) => item.status !== "completed"); if (!task) throw new Error("No active task"); await request(`/tasks/${task.id}`, { method: "PATCH", headers: headers(`ui-task-${status}-${Date.now()}`), body: JSON.stringify({ status }) }); if (status === "completed") await request(`/tasks/${task.id}/structured-outcome`, { method: "POST", headers: headers(`ui-structured-outcome-${Date.now()}`), body: JSON.stringify({ action_type_evidence: "Synthetic water continuity intervention completed", completion_quantities: { liters: 25 }, completed_at: new Date().toISOString(), residual_need: "Continue monitoring next shift", verified_by: "operator" }) }); const scenario = await request<Scenario>("/decision-loop/scenario", { headers: headers() }); return reads(scenario, flow.recommendation); }
