import { useState } from "react";
import { demoWorkspace, type WorkspaceData } from "./fixtures";
import { printTaskPacket, queueCommand, readOutbox, syncOutbox } from "./offline";

type ViewState = "ready" | "loading" | "offline" | "unauthorized" | "error" | "empty";

function StateBanner({ state, setState }: { state: ViewState; setState: (value: ViewState) => void }) { const labels: Record<ViewState, string> = { ready: "Connected", loading: "Loading evidence and projections…", offline: "Offline · showing last known synthetic snapshot", unauthorized: "Unauthorized · sign in with an operator identity", error: "Error · read-only feeds unavailable", empty: "No scoped shelter data" }; return <div className={`state-banner state-${state}`} role="status"><strong>{labels[state]}</strong><span aria-hidden="true"> · </span><button type="button" onClick={() => setState("ready")}>Retry</button><button type="button" onClick={() => setState("offline")}>Simulate offline</button></div>; }

function DecisionOverview({ data }: { data: WorkspaceData }) { return <section className="workspace-section" aria-labelledby="decision-title"><div className="section-heading"><div><p className="eyebrow">Decision loop · North Sector</p><h2 id="decision-title">What is failing, what fails next, and why</h2></div><span className="badge">Synthetic demo · policy v1</span></div><div className="signal-grid">{data.projections.map((item) => <article className="signal-card" key={item.resource}><span className="signal-label">{item.resource}</span><strong>{item.time}</strong><span>{item.state}</span><small>{item.freshness}</small></article>)}</div><div className="unknown-box"><strong>Unknown / stale inputs</strong><p>Medicine cold-chain freshness is stale. Contradictory influx evidence remains visible; verify before changing the plan.</p></div></section>; }

function RecommendationPanel({ data }: { data: WorkspaceData }) { const [decision, setDecision] = useState("Pending commander approval"); return <section className="workspace-section" aria-labelledby="recommend-title"><div className="section-heading"><div><p className="eyebrow">Explainable intervention policy</p><h2 id="recommend-title">Compared actions · {decision}</h2></div><span className="badge">No auto-dispatch</span></div><div className="candidate-list">{data.candidates.map((candidate) => <article className="candidate" key={candidate.action}><div className="rank">#{candidate.rank}</div><div><h3>{candidate.action}</h3><p><strong>Why:</strong> {candidate.effect}</p><p><strong>Cost:</strong> {candidate.cost} · <strong>Confidence:</strong> {candidate.confidence}</p><p><strong>Excluded:</strong> {candidate.excluded}</p></div></article>)}</div><div className="approval"><p><strong>Commander decision is explicit.</strong> Approval creates a queue item only; it does not assign or dispatch a task.</p><button type="button" onClick={() => setDecision("Approved · queue-only")}>Approve top action</button><button type="button" onClick={() => setDecision("Rejected · no queue item")}>Reject</button></div></section>; }

function EvidencePanel({ data }: { data: WorkspaceData }) { return <section className="workspace-section" aria-labelledby="evidence-title"><div className="section-heading"><div><p className="eyebrow">Provenance and verification</p><h2 id="evidence-title">Evidence stays traceable</h2></div></div><div className="evidence-list">{data.evidence.map((item) => <article className="evidence-row" key={item.id}><div><strong>{item.claim}</strong><small>{item.id} · {item.source}</small></div><span className="text-status">{item.state}</span></article>)}</div><p className="verification-note"><strong>Verification queue candidate:</strong> confirm the influx claim because it changes water and medical demand projections.</p></section>; }

function OperationsPanel({ data }: { data: WorkspaceData }) { return <section className="workspace-section" aria-labelledby="ops-title"><div className="section-heading"><div><p className="eyebrow">Operational state</p><h2 id="ops-title">Readiness, routes, queues, and tasks</h2></div></div><div className="ops-grid"><div><h3>Resources</h3>{data.resources.map((item) => <p className="ops-row" key={item.id}><strong>{item.name}</strong><span>{item.readiness} · {item.route}</span><small>{item.task}</small></p>)}</div><div><h3>Response queue</h3>{data.queue.map((item) => <p className="ops-row" key={item.id}><strong>{item.title}</strong><span>{item.status}</span></p>)}<h3>Task lifecycle</h3>{data.tasks.map((item) => <p className="ops-row" key={item.id}><strong>{item.resource}</strong><span>{item.status}</span><small>{item.outcome}</small></p>)}</div></div></section>; }

function SpatialList({ data }: { data: WorkspaceData }) { return <section className="workspace-section" aria-labelledby="spatial-title"><div className="section-heading"><div><p className="eyebrow">Bounded GeoJSON · accessible fallback</p><h2 id="spatial-title">Incident locations</h2></div></div><ul className="spatial-list">{data.places.map((place) => <li key={place.id}><strong>{place.label}</strong><span>{place.state} · coordinates {place.coordinates}</span><small>Source ID: {place.id} · synthetic demo</small></li>)}</ul></section>; }

function OfflinePanel({ data }: { data: WorkspaceData }) { const [count, setCount] = useState(0); const [message, setMessage] = useState("No commands queued"); const [lastSync, setLastSync] = useState(() => localStorage.getItem("field-last-sync") ?? "not connected"); async function refresh() { try { setCount((await readOutbox()).length); } catch { setMessage("Storage unavailable · use paper/radio fallback"); } } return <section className="workspace-section" aria-labelledby="offline-title"><div className="section-heading"><div><p className="eyebrow">Field PWA · server authority</p><h2 id="offline-title">Offline command outbox</h2></div><span className="badge">Last sync: {lastSync}</span></div><p>Only assigned task packets and command metadata are cached. No coordinates or personal data are stored.</p><p><strong>{count}</strong> unsent · failed/conflicted items remain for retry. {message}</p><div className="approval"><button type="button" onClick={() => void refresh()}>Refresh outbox</button><button type="button" onClick={() => void syncOutbox().then((result) => { const stamp = new Date().toISOString(); localStorage.setItem("field-last-sync", stamp); setLastSync(stamp); setMessage(`${result.accepted} accepted/replayed · ${result.conflicts} conflicts · ${result.rejected} rejected`); return refresh(); }).catch(() => setMessage("Sync failed · commands retained"))}>Retry sync</button><button type="button" onClick={() => void queueCommand({ command_id: `demo-${Date.now()}`, aggregate_id: data.tasks[0]?.id ?? "task-demo", sequence: 1, kind: "acknowledgement", client_timestamp: new Date().toISOString(), payload: { status: "acknowledged" }, tenant_id: "org_demo", workspace_id: "evt_demo" }).then(refresh).catch(() => setMessage("Storage failure · use radio fallback"))}>Queue acknowledgement</button><button type="button" onClick={() => printTaskPacket(data.tasks[0] ?? { id: "task-demo", resource: "assigned resource", status: "assigned" })}>Print task packet</button></div><p className="verification-note"><strong>Paper/radio fallback:</strong> read task ID, destination, status, and time to the commander. Server reconciliation is authoritative.</p></section>; }

export function OperatorWorkspace() { const [state, setState] = useState<ViewState>("ready"); if (state === "loading") return <main className="shell"><StateBanner state={state} setState={setState} /><p className="loading-panel" aria-live="polite">Loading scoped decision snapshot…</p></main>; if (["unauthorized", "error", "empty"].includes(state)) return <main className="shell"><StateBanner state={state} setState={setState} /><section className="empty-panel"><h1>{state === "unauthorized" ? "Operator access required" : state === "empty" ? "Workspace is empty" : "Read-only feed unavailable"}</h1><p>Nothing is inferred or silently replaced. Retry when the scoped API is available.</p></section></main>; return <main className="shell"><StateBanner state={state} setState={setState} /><header className="workspace-hero"><p className="eyebrow">Shelter Survival Intelligence · Operator workspace</p><h1>From signal to accountable action.</h1><p>One bounded view of failure, runway, intervention trade-offs, evidence provenance, and commander decisions. Last snapshot: 30 Aug 2026 · 10:30Z.</p></header><DecisionOverview data={demoWorkspace} /><RecommendationPanel data={demoWorkspace} /><EvidencePanel data={demoWorkspace} /><OperationsPanel data={demoWorkspace} /><OfflinePanel data={demoWorkspace} /><SpatialList data={demoWorkspace} /></main>; }
